Description:
  This template is built and deployed by the infrastructure pipeline in various stages (staging/production) as required.
  It specifies the resources that need to be created, like the SageMaker Endpoint. It can be extended to include resources like
  AutoScalingPolicy, API Gateway, etc,. as required.
Parameters:
  SageMakerProjectName:
    Type: String
    Description: Name of the project
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-zA-Z](-*[a-zA-Z0-9])*
  ModelExecutionRoleArn:
    Type: String
    Description: Execution role used for deploying the model.
  ModelPackageName:
    Type: String
    Description: The trained Model Package Name
  StageName:
    Type: String
    Description:
      The name for a project pipeline stage, such as Staging or Prod, for
      which resources are provisioned and deployed.
  EndpointInstanceCount:
    Type: Number
    Description: Number of instances to launch for the endpoint.
    MinValue: 1
  EndpointInstanceType:
    Type: String
    Description: The ML compute instance type for the endpoint.
  DataCaptureUploadPath:
    Type: String
    Description: The s3 path to which the captured data is uploaded.
  SamplingPercentage:
    Type: Number
    Description: The sampling percentage
    MinValue: 0
    MaxValue: 100
  EnableDataCapture:
    Description: Enable Data capture.
    Default: true
    Type: String
    AllowedValues: [true, false]   
  MinInstanceCount:
    Description: Minimum number of instances created
    Type: String
    Default: '1'
  MaxInstanceCount:
    Description: Maximum number of instances created during autoscaling
    Type: String
    Default: '1'
  SageMakerVariantInvocationsPerInstance:
      Type: Number
      Default: '60'
      Description: SageMakerVariantInvocationsPerInstance is the average number of times per minute that each instance for a variant is invoked
  VariantName:
      Description: The name of the production variant.
      Type: String
      Default: "Defult"
  AutoscaleCoolDownPeriod:
      Type: Number
      Default: '600'
      Description: The amount of time, in seconds, after a scaling activity completes before any further trigger-related scaling activities can start

Resources:
  Model:
    Type: AWS::SageMaker::Model
    Properties:
      Containers:
         - ModelPackageName: !Ref ModelPackageName
      ExecutionRoleArn: !Ref ModelExecutionRoleArn

  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: !Ref EndpointInstanceCount
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt Model.ModelName
          VariantName: !Ref VariantName
              
      DataCaptureConfig:
          EnableCapture: !Ref EnableDataCapture 
          InitialSamplingPercentage: !Ref SamplingPercentage
          DestinationS3Uri: !Ref DataCaptureUploadPath
          CaptureOptions:
            - CaptureMode: Input
            - CaptureMode: Output
          CaptureContentTypeHeader:
            CsvContentTypes:
              - "text/csv"

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub ${SageMakerProjectName}-${StageName}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName

  AutoScalingTargetSagemaker:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      DependsOn: Endpoint
      Properties:
          MaxCapacity: !Ref MaxInstanceCount
          MinCapacity: !Ref MinInstanceCount
          ResourceId:
              Fn::Join:
              - ''
              - - endpoint
                - "/"
                - Fn::GetAtt:
                  - EndpointConfig
                  - EndpointConfigName
                - "/variant/"
                - Ref: VariantName
          RoleARN:
              Fn::GetAtt:
              - AutoScalingPolicyRole
              - Arn
          ScalableDimension: sagemaker:variant:DesiredInstanceCount
          ServiceNamespace: sagemaker
          
  AutoScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      DependsOn: AutoScalingTargetSagemaker
      Properties:
          PolicyName: SageMakerEndpointInvocationScalingPolicy
          PolicyType: TargetTrackingScaling
          ScalingTargetId: !Ref AutoScalingTargetSagemaker
          TargetTrackingScalingPolicyConfiguration:
              PredefinedMetricSpecification:
                  PredefinedMetricType: SageMakerVariantInvocationsPerInstance
              ScaleInCooldown: !Ref AutoscaleCoolDownPeriod
              ScaleOutCooldown: !Ref AutoscaleCoolDownPeriod
              TargetValue: !Ref SageMakerVariantInvocationsPerInstance
              
  AutoScalingPolicyRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Principal:
                  Service: sagemaker.amazonaws.com
                Action:
                - sts:AssumeRole
          Policies:
          - PolicyName: AutoscalingPolicySagemaker
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action:
                  - sagemaker:DescribeEndpoint
                  - sagemaker:DescribeEndpointConfig
                  - sagemaker:UpdateEndpointWeightsAndCapacities
                  Resource: "*"
                - Action:
                  - application-autoscaling:*
                  Effect: Allow
                  Resource: "*"
                - Action: iam:CreateServiceLinkedRole
                  Effect: Allow
                  Resource: arn:aws:iam::*:role/aws-service-role/sagemaker.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_SageMakerEndpoint
                  Condition:
                    StringLike:
                      iam:AWSServiceName: sagemaker.application-autoscaling.amazonaws.com
                - Effect: Allow
                  Action:
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DeleteAlarms
                  Resource: "*"
          RoleName: 'AutoScalingPolicyRole'

